'use client';

import { PageHeader } from '@/components/ui/page-header';
import { useToast } from '@/components/ui/toast';
import { useConfirm } from '@/components/ui/confirm-dialog';
import { useMemo, useState } from 'react';
import { ChevronLeft, Pencil, Plus, Trash2 } from 'lucide-react';
import type { RosterAssignmentDto } from '@smart-hospital/shared';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Button } from '@/components/ui/button';
import { FormDrawer } from '@/components/ui/form-drawer';
import { Field, Select } from '@/components/ui/field';
import { ExportMenu } from '@/components/ui/export-menu';
import { useAbility } from '@/lib/auth-store';
import { useStaff } from '@/lib/hooks/use-hr';
import { useCatalog } from '@/lib/hooks/use-masters';
import { useDrShifts, useAllRosterPeriods, useRosterAssignments, useCreateAssignment, useUpdateAssignment, useDeleteAssignment } from '@/lib/hooks/use-duty-roster';
import { fmtDate, staffLabel } from './util';

export function AssignView({ onBack }: { onBack: () => void }) {
  const ability = useAbility();
  const canAdd = ability.can('duty_roster', 'add');
  const canEdit = ability.can('duty_roster', 'edit');
  const canDelete = ability.can('duty_roster', 'delete');

  const shifts = useDrShifts();
  const periods = useAllRosterPeriods();
  const staff = useStaff(undefined, { size: 200 });
  const floors = useCatalog('floor', { size: 100 });
  const departments = useCatalog('department', { size: 100 });
  const list = useRosterAssignments();
  const create = useCreateAssignment();
  const update = useUpdateAssignment();
  const del = useDeleteAssignment();
  const toast = useToast();
  const confirm = useConfirm();

  const [search, setSearch] = useState('');
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<RosterAssignmentDto | null>(null);
  const [shiftId, setShiftId] = useState('');
  const [rosterId, setRosterId] = useState('');
  const [staffUserId, setStaffUserId] = useState('');
  const [floorId, setFloorId] = useState('');
  const [departmentId, setDepartmentId] = useState('');
  const [error, setError] = useState('');

  const allPeriods = periods.data ?? [];
  const periodsForShift = useMemo(() => allPeriods.filter((p) => p.shiftId === shiftId), [allPeriods, shiftId]);

  const rows = useMemo(() => {
    const all = list.data?.data ?? [];
    const q = search.trim().toLowerCase();
    return q ? all.filter((a) => `${a.staffName} ${a.shiftName} ${a.departmentName ?? ''} ${a.floorName ?? ''}`.toLowerCase().includes(q)) : all;
  }, [list.data, search]);

  function openAdd() {
    setEditing(null);
    setShiftId(''); setRosterId(''); setStaffUserId(''); setFloorId(''); setDepartmentId(''); setError('');
    setOpen(true);
  }
  function openEdit(a: RosterAssignmentDto) {
    setEditing(a);
    const period = allPeriods.find((p) => p.id === a.rosterId);
    setShiftId(period?.shiftId ?? '');
    setRosterId(a.rosterId);
    setStaffUserId(a.staffUserId);
    setFloorId(a.floorId ?? '');
    setDepartmentId(a.departmentId ?? '');
    setError('');
    setOpen(true);
  }
  function pickShift(id: string) {
    setShiftId(id);
    setRosterId(''); // reset date when shift changes
  }
  async function save() {
    if (!rosterId || !staffUserId) { setError('Shift date and staff are required.'); return; }
    const input = { rosterId, staffUserId, floorId: floorId || null, departmentId: departmentId || null };
    if (editing) await update.mutateAsync({ id: editing.id, input });
    else await create.mutateAsync(input);
    setOpen(false);
  }
  async function remove(a: RosterAssignmentDto) {
    const ok = await confirm({
      title: `Remove ${a.staffName} from ${a.shiftName}?`,
      description: 'The assignment is removed. The staff member and shift are kept.',
      confirmLabel: 'Remove assignment',
      tone: 'warning',
    });
    if (!ok) return;
    try {
      await del.mutateAsync(a.id);
      toast.success(`${a.staffName} removed from ${a.shiftName}`);
    } catch (e) {
      toast.error('Could not remove assignment', { description: (e as Error).message });
    }
  }

  const cols: Column<RosterAssignmentDto>[] = [
    { key: 'staffName', header: 'Staff', className: 'font-medium', render: (a) => staffLabel(a.staffName, a.staffNo) },
    { key: 'floorName', header: 'Floor', render: (a) => a.floorName ?? '—' },
    { key: 'departmentName', header: 'Department', render: (a) => a.departmentName ?? '—' },
    { key: 'shiftName', header: 'Roster' },
    { key: 'dates', header: 'Start Date - End Date', render: (a) => `${fmtDate(a.startDate)} - ${fmtDate(a.endDate)}` },
    { key: 'times', header: 'Shift Start - Shift End', render: (a) => `${a.shiftStartLabel} - ${a.shiftEndLabel}` },
    { key: 'generatedByName', header: 'Generated By', render: (a) => (a.generatedByName ? staffLabel(a.generatedByName, a.generatedByNo) : '—') },
  ];

  return (
    <div className="space-y-4">
      <button onClick={onBack} className="flex items-center gap-1 text-sm text-fg-muted hover:text-fg"><ChevronLeft className="h-4 w-4" /> Duty Roster</button>
      <PageHeader
        title="Assign Roster"
        actions={canAdd && <Button onClick={openAdd}><Plus className="h-4 w-4" /> Assign Roster</Button>}
      />

      <DataTable
        columns={cols}
        rows={rows}
        loading={list.isLoading}
        search={search}
        onSearch={setSearch}
        onPage={() => {}}
        onSize={() => {}}
        toolbar={<ExportMenu table={() => ({ title: 'Assign Roster', filename: 'assign-roster', headers: ['Staff', 'Floor', 'Department', 'Roster', 'Start Date - End Date', 'Shift Start - Shift End', 'Generated By'], rows: rows.map((a) => [staffLabel(a.staffName, a.staffNo), a.floorName ?? '', a.departmentName ?? '', a.shiftName, `${fmtDate(a.startDate)} - ${fmtDate(a.endDate)}`, `${a.shiftStartLabel} - ${a.shiftEndLabel}`, a.generatedByName ? staffLabel(a.generatedByName, a.generatedByNo) : '']) })} />}
        rowActions={(canEdit || canDelete) ? (a) => (
          <div className="flex gap-1">
            {canEdit && <button onClick={() => openEdit(a)} aria-label="Edit" title="Edit" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary"><Pencil className="h-4 w-4" /></button>}
            {canDelete && <button onClick={() => remove(a)} aria-label="Delete" title="Delete" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-danger/10 hover:text-danger"><Trash2 className="h-4 w-4" /></button>}
          </div>
        ) : undefined}
      />

      <FormDrawer open={open} title={editing ? 'Edit Assign Roster' : 'Assign Roster'} onClose={() => setOpen(false)} onSubmit={save} submitting={create.isPending || update.isPending} wide>
        <div className="space-y-5">
          {error && <p role="alert" className="rounded-sm bg-danger/10 px-3 py-2 text-sm text-danger">{error}</p>}

          <div>
            <p className="mb-2 text-sm font-semibold">Shift</p>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {(shifts.data ?? []).map((s) => (
                <button key={s.id} type="button" onClick={() => pickShift(s.id)}
                  className={`rounded-md border px-3 py-3 text-center transition ${shiftId === s.id ? 'border-primary bg-primary/10 ring-1 ring-primary' : 'border-border hover:border-primary/60'}`}>
                  <p className="text-sm font-semibold">{s.name}</p>
                  <p className="mt-0.5 text-xs text-fg-muted">{s.startLabel} - {s.endLabel}</p>
                </button>
              ))}
            </div>
          </div>

          <Field label="Shift Date" required>
            <Select value={rosterId} onChange={(e) => setRosterId(e.target.value)} placeholder="Select"
              options={periodsForShift.map((p) => ({ value: p.id, label: `${fmtDate(p.startDate)} - ${fmtDate(p.endDate)}` }))}
              disabled={!shiftId} />
          </Field>

          <Field label="Staff" required>
            <Select value={staffUserId} onChange={(e) => setStaffUserId(e.target.value)} placeholder="Select"
              options={(staff.data?.data ?? []).map((s) => ({ value: s.userId, label: staffLabel(s.name, s.staffNo) }))} />
          </Field>

          <div className="grid grid-cols-2 gap-4">
            <Field label="Floor">
              <Select value={floorId} onChange={(e) => setFloorId(e.target.value)} placeholder="Select"
                options={(floors.data?.data ?? []).map((f) => ({ value: f.id, label: f.name }))} />
            </Field>
            <Field label="Department">
              <Select value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} placeholder="Select"
                options={(departments.data?.data ?? []).map((d) => ({ value: d.id, label: d.name }))} />
            </Field>
          </div>
        </div>
      </FormDrawer>
    </div>
  );
}
