services:
  postgres:
    image: postgres:16-alpine
    container_name: sh_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smarthospital
      POSTGRES_PASSWORD: smarthospital
      POSTGRES_DB: smart_hospital
    ports:
      - "5433:5432"
    volumes:
      - sh_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smarthospital -d smart_hospital"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sh_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - sh_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sh_pgdata:
  sh_redisdata:
