'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Plus, Printer, Pill, Eye, FileText, LogOut } from 'lucide-react';
import type { OpdTab, OpdVisitDto } from '@smart-hospital/shared';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { ExportMenu } from '@/components/ui/export-menu';
import type { ExportTable } from '@/lib/export';
import { OpdForm } from './opd-form';
import { PatientViewPanel } from '@/components/emr/patient-view-panel';
import { VisitDetailsModal } from '@/components/emr/visit-details-modal';
import { PrescriptionBuilder } from '@/components/emr/prescription-builder';
import { ManualPrescriptionModal } from '@/components/emr/manual-prescription-modal';
import { MoveToIpdModal } from '@/components/emr/move-to-ipd-modal';
import { useOpdVisits, useOpdVisitDetail } from '@/lib/hooks/use-clinical';
import { useAbility } from '@/lib/auth-store';
import { printOpdPrescription } from '@/lib/print';

type ViewTab = OpdTab | 'patientView';

const TABS: { value: ViewTab; label: string }[] = [
  { value: 'today', label: 'Today OPD' },
  { value: 'upcoming', label: 'Upcoming OPD' },
  { value: 'old', label: 'Old OPD' },
  { value: 'patientView', label: 'Patient View' },
];

export default function OpdPage() {
  const ability = useAbility();
  const canAdd = ability.can('opd', 'add');
  const canEdit = ability.can('opd', 'edit');
  const canDelete = ability.can('opd', 'delete');
  const params = useSearchParams();
  const [tab, setTab] = useState<ViewTab>('today');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(25);
  const [open, setOpen] = useState(false);

  // Row-action state (Print / Add Prescription / Show / Manual Prescription / Move to IPD)
  const [showId, setShowId] = useState<string | null>(null);
  const [rxTarget, setRxTarget] = useState<{ visitId: string; patientId: string; patientName: string } | null>(null);
  const [manualId, setManualId] = useState<string | null>(null);
  const [printId, setPrintId] = useState<string | null>(null);
  const [moveId, setMoveId] = useState<string | null>(null);

  // Quick-create from the patient list: ?new=1&patientId=…&patientName=…
  const presetPatientId = params.get('patientId') ?? '';
  const presetPatientName = params.get('patientName') ?? '';
  useEffect(() => {
    if (params.get('new') === '1' && canAdd) setOpen(true);
  }, [params, canAdd]);

  // Deep-link from the Appointment list: ?tab=patientView&patientId=…
  useEffect(() => {
    if (params.get('tab') === 'patientView') setTab('patientView');
  }, [params]);

  const isPatientView = tab === 'patientView';
  const { data, isLoading, error } = useOpdVisits(isPatientView ? 'today' : tab, { search, page, size });

  function exportTable(): ExportTable {
    const rows = data?.data ?? [];
    return {
      title: 'OPD Visits',
      filename: 'opd-visits',
      headers: ['OPD No', 'Patient', 'Case ID', 'Appointment Date', 'Generated By', 'Consultant', 'Reference', 'Symptoms', 'Is Antenatal', 'Previous Medical Issue'],
      rows: rows.map((o) => [
        o.opdNo,
        o.patientName,
        o.caseNo ?? '',
        new Date(o.appointmentDate).toLocaleString(),
        o.createdByName ?? '',
        o.consultantName,
        o.reference ?? '',
        o.symptoms ?? '',
        o.isAntenatal ? 'Yes' : 'No',
        o.previousMedicalIssue ?? '',
      ]),
    };
  }

  const columns: Column<OpdVisitDto>[] = [
    {
      key: 'opdNo',
      header: 'OPD No',
      className: 'font-medium',
      render: (o) => (
        <Link href={`/opd/${o.id}`} className="text-primary hover:underline">
          {o.opdNo}
        </Link>
      ),
    },
    { key: 'patientName', header: 'Patient Name' },
    { key: 'caseNo', header: 'Case ID', render: (o) => o.caseNo ?? '—' },
    {
      key: 'appointmentDate',
      header: 'Appointment Date',
      render: (o) => new Date(o.appointmentDate).toLocaleString(),
    },
    { key: 'createdByName', header: 'Generated By', render: (o) => o.createdByName ?? '—' },
    { key: 'consultantName', header: 'Consultant' },
    { key: 'reference', header: 'Reference', render: (o) => o.reference ?? '—' },
    { key: 'symptoms', header: 'Symptoms', className: 'max-w-xs text-fg-muted', render: (o) => o.symptoms ?? '—' },
    { key: 'isAntenatal', header: 'Is Antenatal', render: (o) => (o.isAntenatal ? 'Yes' : 'No') },
    {
      key: 'previousMedicalIssue',
      header: 'Previous Medical Issue',
      className: 'text-fg-muted',
      render: (o) => o.previousMedicalIssue ?? '—',
    },
  ];

  return (
    <div className="space-y-4">
      <PageHeader
        title="OPD – Out Patient"
        description="Register outpatient visits with charge capture"
        actions={canAdd && (
          <Button onClick={() => setOpen(true)}>
            <Plus className="h-4 w-4" /> Add Patient
          </Button>
        )}
      />

      <Tabs
        tabs={TABS}
        value={tab}
        onChange={(t) => {
          setTab(t);
          setPage(1);
        }}
      />

      {isPatientView ? (
        <PatientViewPanel initialPatientId={presetPatientId || undefined} />
      ) : (
        <DataTable
          columns={columns}
          rows={data?.data ?? []}
          meta={data?.meta}
          loading={isLoading}
          error={error ? 'Failed to load OPD visits' : undefined}
          search={search}
          onSearch={(v) => {
            setSearch(v);
            setPage(1);
          }}
          onPage={setPage}
          onSize={(s) => {
            setSize(s);
            setPage(1);
          }}
          toolbar={<ExportMenu table={exportTable} />}
          rowActions={(o) => (
            <>
              <ActionIcon label="Print" icon={Printer} onClick={() => setPrintId(o.id)} />
              <ActionIcon
                label="Add Prescription"
                icon={Pill}
                onClick={() => setRxTarget({ visitId: o.id, patientId: o.patientId, patientName: o.patientName })}
              />
              <ActionIcon label="Show" icon={Eye} onClick={() => setShowId(o.id)} />
              <ActionIcon label="Manual Prescription" icon={FileText} onClick={() => setManualId(o.id)} />
              <ActionIcon label="Move to IPD" icon={LogOut} onClick={() => setMoveId(o.id)} />
            </>
          )}
        />
      )}

      <OpdForm
        open={open}
        onClose={() => setOpen(false)}
        initialPatientId={presetPatientId}
        initialPatientLabel={presetPatientName}
      />

      <VisitDetailsModal id={showId} open={!!showId} onClose={() => setShowId(null)} canEdit={canEdit} canDelete={canDelete} />

      <PrescriptionBuilder
        open={!!rxTarget}
        onClose={() => setRxTarget(null)}
        patientName={rxTarget?.patientName}
        scope={{ patientId: rxTarget?.patientId ?? '', encounterType: 'opd', encounterId: rxTarget?.visitId }}
      />

      <ManualPrescriptionModal id={manualId} open={!!manualId} onClose={() => setManualId(null)} />

      <MoveToIpdModal id={moveId} open={!!moveId} onClose={() => setMoveId(null)} />

      {printId && <PrintTrigger id={printId} onDone={() => setPrintId(null)} />}
    </div>
  );
}

/** Fetches the visit detail once, prints it, then reports back so the caller can clear state. */
function PrintTrigger({ id, onDone }: { id: string; onDone: () => void }) {
  const { data } = useOpdVisitDetail(id);

  useEffect(() => {
    if (data) {
      printOpdPrescription(data);
      onDone();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  return null;
}

function ActionIcon({
  label,
  icon: Icon,
  onClick,
}: {
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      aria-label={label}
      title={label}
      className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary"
    >
      <Icon className="h-4 w-4" />
    </button>
  );
}
