'use client';

import { useState } from 'react';
import { Eye, CreditCard, Printer, Plus, FlaskConical } from 'lucide-react';
import type { InvoiceDto, DiagnosticTestDto, Modality } from '@smart-hospital/shared';
import { DataTable, type Column, type SortState } from '@/components/ui/data-table';
import { useConfirmDelete } from '@/components/ui/confirm-dialog';
import { useToast } from '@/components/ui/toast';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ExportMenu } from '@/components/ui/export-menu';
import type { ExportTable } from '@/lib/export';
import { useInvoices } from '@/lib/hooks/use-clinical';
import { useDiagnosticTests, useDeleteDiagnosticTest } from '@/lib/hooks/use-departments';
import { useAbility } from '@/lib/auth-store';
import { DiagnosticBillForm } from '@/components/emr/diagnostic-bill-form';
import { DiagnosticBillDetailsModal } from '@/components/emr/diagnostic-bill-details-modal';
import { DiagnosticPaymentsModal } from '@/components/emr/diagnostic-payments-modal';
import { DiagnosticTestForm } from '@/components/emr/diagnostic-test-form';
import { DiagnosticTestDetailsModal } from '@/components/emr/diagnostic-test-details-modal';
import { printDiagnosticBill } from '@/lib/print';

type Tab = 'bills' | 'tests';

/** Full-parity Pathology/Radiology department page — configured by modality + title, shared by both routes. */
export function DiagnosticDeptPage({ modality, title }: { modality: Modality; title: string }) {
  const ability = useAbility();
  const canAdd = ability.can(modality, 'add');
  const canDelete = ability.can(modality, 'delete');

  const confirmDelete = useConfirmDelete();
  const toast = useToast();
  const [tab, setTab] = useState<Tab>('bills');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  // Was hardcoded 25 with `onSize={() => {}}`: the rows-per-page control
  // rendered and reacted, but the query never changed, so picking 100 did
  // nothing at all.
  const [size, setSize] = useState(25);
  const [sort, setSort] = useState<SortState | undefined>();

  const [billOpen, setBillOpen] = useState(false);
  const [billDetailId, setBillDetailId] = useState<string | null>(null);
  const [paymentsId, setPaymentsId] = useState<string | null>(null);

  const [testFormOpen, setTestFormOpen] = useState(false);
  const [editingTest, setEditingTest] = useState<DiagnosticTestDto | null>(null);
  const [detailTest, setDetailTest] = useState<DiagnosticTestDto | null>(null);

  const sortParam = sort ? `${sort.key}:${sort.dir}` : undefined;
  const invoices = useInvoices(modality, { search, page, size, sort: sortParam });
  const tests = useDiagnosticTests(modality, { search, page, size, sort: sortParam });
  const deleteTest = useDeleteDiagnosticTest(modality);

  function switchTab(t: Tab) {
    setTab(t);
    setPage(1);
    setSearch('');
    // The two tabs sort on different columns, so a sort carried across would
    // reference a key the other list has never heard of.
    setSort(undefined);
  }

  /** asc → desc → cleared, so a third click restores the default ordering. */
  function toggleSort(key: string) {
    setSort((cur) =>
      cur?.key !== key ? { key, dir: 'asc' } : cur.dir === 'asc' ? { key, dir: 'desc' } : undefined,
    );
    setPage(1);
  }

  function billExportTable(): ExportTable {
    const rows = invoices.data?.data ?? [];
    return {
      title: `${title} Bill`,
      filename: `${modality}-bills`,
      headers: ['Bill No', 'Case ID', 'Bill Date', 'Patient Name', 'Generated By', 'Reference Doctor', 'Previous Report Value', 'Amount', 'Discount', 'Tax', 'Net Amount', 'Paid', 'Balance'],
      rows: rows.map((i) => [
        i.billNo, i.caseNo ?? '', new Date(i.billDate).toLocaleString(), i.patientName, i.createdByName ?? '', i.referenceDoctor ?? '', i.previousReportValue ?? '',
        i.subtotal.toFixed(2), i.discount.toFixed(2), i.tax.toFixed(2), i.netAmount.toFixed(2), i.paid.toFixed(2), i.balance.toFixed(2),
      ]),
    };
  }

  const billCols: Column<InvoiceDto>[] = [
    { key: 'billNo', sortable: true, header: 'Bill No', className: 'font-medium' },
    { key: 'caseNo', header: 'Case ID', render: (i) => i.caseNo ?? '—' },
    { key: 'billDate', sortable: true, header: 'Bill Date', render: (i) => new Date(i.billDate).toLocaleString() },
    { key: 'patientName', header: 'Patient Name' },
    { key: 'createdByName', header: 'Generated By', render: (i) => i.createdByName ?? '—' },
    { key: 'referenceDoctor', header: 'Reference Doctor', render: (i) => i.referenceDoctor || i.consultantName || '—' },
    { key: 'previousReportValue', header: 'Previous Report Value', sortable: true, render: (i) => i.previousReportValue ?? '—' },
    { key: 'subtotal', sortable: true, header: 'Amount (#)', className: 'tabular', render: (i) => i.subtotal.toFixed(2) },
    { key: 'discount', sortable: true, header: 'Discount', className: 'tabular', render: (i) => i.discount.toFixed(2) },
    { key: 'tax', sortable: true, header: 'Tax (#)', className: 'tabular', render: (i) => i.tax.toFixed(2) },
    { key: 'netAmount', sortable: true, header: 'Net Amount (#)', className: 'tabular', render: (i) => i.netAmount.toFixed(2) },
    { key: 'paid', sortable: true, header: 'Paid (#)', className: 'tabular', render: (i) => i.paid.toFixed(2) },
    {
      key: 'balance', header: 'Balance (#)', className: 'tabular',
      render: (i) => <span className={i.balance > 0 ? 'text-warning' : 'text-success'}>{i.balance.toFixed(2)}</span>,
    },
  ];

  function testExportTable(): ExportTable {
    const rows = tests.data?.data ?? [];
    return {
      title: `${title} Test`,
      filename: `${modality}-tests`,
      headers: ['Test Name', 'Short Name', 'Test Type', 'Category', 'Sub Category', 'Method', 'Report Days', 'Tax (%)', 'Charge', 'Amount'],
      rows: rows.map((t) => [t.name, t.shortName ?? '', t.testType ?? '', t.categoryName ?? '', t.subCategory ?? '', t.method ?? '', String(t.reportDays), t.taxPercent.toFixed(2), t.standardCharge.toFixed(2), t.charge.toFixed(2)]),
    };
  }

  const testCols: Column<DiagnosticTestDto>[] = [
    { key: 'name', sortable: true, header: 'Test Name', className: 'font-medium' },
    { key: 'shortName', sortable: true, header: 'Short Name', render: (t) => t.shortName ?? '—' },
    { key: 'testType', sortable: true, header: 'Test Type', render: (t) => t.testType ?? '—' },
    { key: 'categoryName', header: 'Category', render: (t) => t.categoryName ?? '—' },
    { key: 'subCategory', sortable: true, header: 'Sub Category', render: (t) => t.subCategory ?? '—' },
    { key: 'method', sortable: true, header: 'Method', render: (t) => t.method ?? '—' },
    { key: 'reportDays', sortable: true, header: 'Report Days', className: 'tabular' },
    { key: 'taxPercent', sortable: true, header: 'Tax (%)', className: 'tabular', render: (t) => t.taxPercent.toFixed(2) },
    { key: 'standardCharge', sortable: true, header: 'Charge (#)', className: 'tabular', render: (t) => t.standardCharge.toFixed(2) },
    { key: 'charge', sortable: true, header: 'Amount (#)', className: 'tabular', render: (t) => t.charge.toFixed(2) },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">{title}</h1>
          <p className="text-sm text-fg-muted">Bills, test catalog, and reporting</p>
        </div>
        <div className="flex items-center gap-2">
          {tab === 'bills' && (
            <>
              <Button variant="secondary" onClick={() => switchTab('tests')}>
                <FlaskConical className="h-4 w-4" /> {title} Test
              </Button>
              {canAdd && <Button onClick={() => setBillOpen(true)}><Plus className="h-4 w-4" /> Generate Bill</Button>}
            </>
          )}
          {tab === 'tests' && (
            <>
              <Button variant="secondary" onClick={() => switchTab('bills')}>
                {title} Bill
              </Button>
              {canAdd && <Button onClick={() => { setEditingTest(null); setTestFormOpen(true); }}><Plus className="h-4 w-4" /> Add {title} Test</Button>}
            </>
          )}
        </div>
      </div>

      <Tabs
        tabs={[
          { value: 'bills', label: `${title} Bill` },
          { value: 'tests', label: `${title} Test` },
        ]}
        value={tab}
        onChange={(t) => switchTab(t as Tab)}
      />

      {tab === 'bills' && (
        <DataTable
          columns={billCols}
          rows={invoices.data?.data ?? []}
          meta={invoices.data?.meta}
          loading={invoices.isLoading}
          search={search}
          onSearch={(v) => { setSearch(v); setPage(1); }}
          onPage={setPage}
          onSize={(v) => { setSize(v); setPage(1); }}
          sort={sort}
          onSort={toggleSort}
          toolbar={<ExportMenu table={billExportTable} />}
          rowActions={(i) => (
            <>
              <button onClick={() => setBillDetailId(i.id)} aria-label="Details" title="Bill Details" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Eye className="h-4 w-4" />
              </button>
              <button onClick={() => setPaymentsId(i.id)} aria-label="Payments" title="Payments" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <CreditCard className="h-4 w-4" />
              </button>
              <button onClick={() => printDiagnosticBill(title, i)} aria-label="Print" title="Print" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Printer className="h-4 w-4" />
              </button>
            </>
          )}
        />
      )}

      {tab === 'tests' && (
        <DataTable
          columns={testCols}
          rows={tests.data?.data ?? []}
          meta={tests.data?.meta}
          loading={tests.isLoading}
          search={search}
          onSearch={(v) => { setSearch(v); setPage(1); }}
          onPage={setPage}
          onSize={(v) => { setSize(v); setPage(1); }}
          sort={sort}
          onSort={toggleSort}
          toolbar={<ExportMenu table={testExportTable} />}
          rowActions={(t) => (
            <button onClick={() => setDetailTest(t)} aria-label="Details" title="Details" className="flex h-7 items-center gap-1 rounded-sm px-2 text-xs text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Eye className="h-4 w-4" /> Details
            </button>
          )}
        />
      )}

      <DiagnosticBillForm open={billOpen} modality={modality} title={title} onClose={() => setBillOpen(false)} />
      <DiagnosticBillDetailsModal id={billDetailId} modality={modality} title={title} open={!!billDetailId} onClose={() => setBillDetailId(null)} />
      <DiagnosticPaymentsModal id={paymentsId} open={!!paymentsId} onClose={() => setPaymentsId(null)} />

      <DiagnosticTestForm open={testFormOpen} modality={modality} test={editingTest} onClose={() => setTestFormOpen(false)} />
      <DiagnosticTestDetailsModal
        test={detailTest}
        modality={modality}
        open={!!detailTest}
        onClose={() => setDetailTest(null)}
        onEdit={() => { setEditingTest(detailTest); setDetailTest(null); setTestFormOpen(true); }}
        onDelete={async () => {
          if (!detailTest || !canDelete) return;
          if (!(await confirmDelete(`test ${detailTest.name}`))) return;
          try {
            await deleteTest.mutateAsync(detailTest.id);
            toast.success(`${detailTest.name} deleted`);
            setDetailTest(null);
          } catch (e) {
            toast.error('Could not delete test', { description: (e as Error).message });
          }
        }}
      />
    </div>
  );
}
