#!/usr/bin/env bash
#
# Per-deploy build + migrate + restart. Runs ON the server, as ubuntu, via
# deploy.sh. Assumes bootstrap.sh has already run.
#
#   env → install → build → backup → migrate → [seed] → archive → restart → verify
#
set -euo pipefail

APP_ROOT=/opt/smart-hospital
APP_DIR="$APP_ROOT/app"
SHARED_DIR="$APP_ROOT/shared"
ENV_FILE="$SHARED_DIR/.env.production"
SVC_USER=hms
PG_DB=smart_hospital
PG_USER=smarthospital

DO_SEED="${DO_SEED:-0}"
SKIP_BUILD="${SKIP_BUILD:-0}"
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-}"

log()  { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

cd "$APP_DIR"

# ── environment ─────────────────────────────────────────────────────────────
# Written before the build, deliberately: NEXT_PUBLIC_* is inlined into the
# client bundle at build time. Writing it afterwards would be a silent no-op.
log "Environment"
if [[ -f "$ENV_FILE" ]]; then
  ok "reusing $ENV_FILE (secrets preserved)"
  JWT_A=$(sudo grep -m1 '^JWT_ACCESS_SECRET=' "$ENV_FILE" | cut -d= -f2-)
  JWT_R=$(sudo grep -m1 '^JWT_REFRESH_SECRET=' "$ENV_FILE" | cut -d= -f2-)
else
  JWT_A="$(openssl rand -hex 32)"
  JWT_R="$(openssl rand -hex 32)"
  ok "generated fresh JWT secrets"
fi

PG_PASS=$(sudo cat "$SHARED_DIR/.pgpass" 2>/dev/null || echo '')
[[ -n "$PG_PASS" ]] || die "missing $SHARED_DIR/.pgpass — re-run bootstrap"

# Same origin behind nginx, so this stays relative and CORS never applies.
sudo tee "$ENV_FILE" >/dev/null <<ENV
# Generated by deploy/release.sh — do not edit by hand, do not commit.
NODE_ENV=production
DATABASE_URL=postgresql://${PG_USER}:${PG_PASS}@localhost:5432/${PG_DB}?schema=public
JWT_ACCESS_SECRET=${JWT_A}
JWT_REFRESH_SECRET=${JWT_R}
JWT_ACCESS_TTL=900s
JWT_REFRESH_TTL=7d
API_PORT=4000
CORS_ORIGINS=${PUBLIC_ORIGIN:-http://localhost:3001}
NEXT_PUBLIC_API_URL=/api/v1
ENV
sudo chown root:"$SVC_USER" "$ENV_FILE"
sudo chmod 640 "$ENV_FILE"
ok "$ENV_FILE written (0640 root:$SVC_USER)"

# Two build-time files, split by sensitivity — the web one is world-readable
# once the tree is opened up for the service user, so it must carry no secrets.
#
#   apps/web/.env.production : NEXT_PUBLIC_* only (public by definition —
#                              it gets inlined into the client bundle anyway)
#   .env                     : DATABASE_URL for prisma migrate, 0600 ubuntu
printf 'NEXT_PUBLIC_API_URL=/api/v1\n' > "$APP_DIR/apps/web/.env.production"
chmod 644 "$APP_DIR/apps/web/.env.production"

printf 'DATABASE_URL=postgresql://%s:%s@localhost:5432/%s?schema=public\n' \
  "$PG_USER" "$PG_PASS" "$PG_DB" > "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"
ok "build-time env split (secrets stay out of the web bundle dir)"

# ── install ─────────────────────────────────────────────────────────────────
# Always runs, including when the build is skipped: even a CI deploy that ships
# prebuilt artifacts still needs runtime node_modules on the server. It is ~2
# minutes and idempotent — it was never the slow part; the build was.
log "Dependencies"
corepack enable >/dev/null 2>&1 || true
# apps/e2e is in the workspace, so a plain install pulls @playwright/test —
# whose postinstall downloads ~300 MB of browsers. Useless on a server that
# never runs the tests, and painful on this disk and link.
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
pnpm install --frozen-lockfile --prefer-offline 2>&1 | tail -3
ok "installed (playwright browsers skipped)"

# ── prisma client ───────────────────────────────────────────────────────────
# Must run on EVERY release, not only when we build here. The client is
# generated into the server's own node_modules from the rsynced schema; CI ships
# dist but never node_modules, so the artifact path cannot supply it.
#
# This used to sit inside the build block, so every CI deploy (SKIP_BUILD=1)
# skipped it. The client stayed frozen at whatever schema was current the last
# time someone ran a full on-server build, and every column added by a migration
# after that was invisible at runtime — findMany simply never selected it, so
# the API returned rows with the new fields silently missing and no error
# anywhere. Caught when appointment paymentNote/transactionId/serialNo came back
# absent from a server whose database definitely had the columns.
log "Prisma client"
pnpm --filter @smart-hospital/api prisma:generate 2>&1 | tail -2
ok "prisma client matches the schema on disk"

# ── reclaim build outputs ───────────────────────────────────────────────────
# The Permissions step below hands .next to hms so the service can write its
# runtime cache. That makes the outputs undeletable by ubuntu, which is who
# runs the *next* deploy — so every deploy after the first would fail, either
# here on rebuild or in CI when it unpacks fresh artifacts. Take them back
# first; they get handed to hms again at the end.
if [[ -e "$APP_DIR/apps/web/.next" ]]; then
  sudo chown -R ubuntu:ubuntu "$APP_DIR/apps/web/.next" \
    "$APP_DIR/apps/api/dist" "$APP_DIR/packages/shared/dist" 2>/dev/null || true
  ok "reclaimed build outputs from $SVC_USER"
fi

if [[ "$SKIP_BUILD" != "1" ]]; then
  # ── build ─────────────────────────────────────────────────────────────────
  # Sequential and heap-capped. turbo parallelises by default and two of these
  # builds at once will not fit in 954 MiB even with swap behind them.
  log "Build (serialised — this is the slow part, 15–30 min)"

  export NODE_OPTIONS="--max-old-space-size=1400"
  export NEXT_TELEMETRY_DISABLED=1

  echo "  · packages/shared"
  pnpm --filter @smart-hospital/shared build 2>&1 | tail -2
  ok "shared → dist (must precede the API; it imports the compiled JS)"

  echo "  · apps/api"
  pnpm --filter @smart-hospital/api build 2>&1 | tail -2
  [[ -f apps/api/dist/src/main.js ]] || die "API build produced no dist/src/main.js"
  ok "api → dist"

  echo "  · apps/web  (heaviest step)"
  pnpm --filter @smart-hospital/web build 2>&1 | tail -6
  [[ -d apps/web/.next ]] || die "web build produced no .next"
  ok "web → .next"
fi

# ── backup before migrating ─────────────────────────────────────────────────
log "Pre-migration backup"
BACKUP="$APP_ROOT/backups/pre-deploy-$(date +%Y%m%d-%H%M%S).sql.gz"
sudo -u postgres pg_dump "$PG_DB" | gzip | sudo tee "$BACKUP" >/dev/null
ok "$(basename "$BACKUP") ($(sudo du -h "$BACKUP" | cut -f1))"

# ── migrate ─────────────────────────────────────────────────────────────────
log "Migrations"
set -a; . <(sudo cat "$ENV_FILE"); set +a
pnpm --filter @smart-hospital/api prisma:deploy 2>&1 | tail -6
ok "schema up to date"

# ── seed ────────────────────────────────────────────────────────────────────
# The guard fails CLOSED. An earlier version queried "Patient", but Prisma maps
# models to snake_case, so the query errored, 2>/dev/null swallowed it, and the
# count defaulted to 0 — the guard would have waved a seed straight over live
# patient data. Now: the tables are named explicitly, and anything unexpected
# (missing table, psql failure, non-numeric result) aborts instead of seeding.
if [[ "$DO_SEED" == "1" ]]; then
  log "Seed"

  seed_blocked=0
  for tbl in patient '"user"'; do
    n=$(sudo -u postgres psql -tAd "$PG_DB" -c "SELECT count(*) FROM $tbl" 2>&1 | tr -d '[:space:]')
    if ! [[ "$n" =~ ^[0-9]+$ ]]; then
      warn "cannot read $tbl — refusing to seed"
      warn "  psql said: ${n:0:120}"
      seed_blocked=1
    elif [[ "$n" -gt 0 ]]; then
      warn "$tbl already holds $n rows — refusing to seed over existing data"
      seed_blocked=1
    else
      ok "$tbl is empty"
    fi
  done

  if [[ "$seed_blocked" == "1" ]]; then
    warn "seed skipped. To reset deliberately, restore $BACKUP first, then re-run with --seed"
  else
    pnpm --filter @smart-hospital/api prisma:seed 2>&1 | tail -5
    ok "seeded"
  fi
fi

# ── archive build outputs for fast rollback ─────────────────────────────────
log "Archive"
STAMP=$(date +%Y%m%d-%H%M%S)
ART="$APP_ROOT/artifacts/build-$STAMP.tar.zst"
sudo tar --zstd -cf "$ART" \
  -C "$APP_DIR" packages/shared/dist apps/api/dist apps/web/.next 2>/dev/null || \
  warn "archive skipped (partial build outputs)"
if [[ -f "$ART" ]]; then
  echo "$STAMP" | sudo tee "$APP_ROOT/artifacts/LATEST" >/dev/null
  ok "$(basename "$ART") ($(sudo du -h "$ART" | cut -f1))"
  # Keep the last 5; disk is ample but there is no reason to hoard.
  sudo sh -c "ls -1t $APP_ROOT/artifacts/build-*.tar.zst 2>/dev/null | tail -n +6 | xargs -r rm -f"
fi

# ── ownership ───────────────────────────────────────────────────────────────
# hms reads the code and writes only Next's runtime cache. Scoped deliberately:
# a blanket `chmod -R a+rX $APP_DIR` would also expose $APP_DIR/.env.
log "Permissions"
sudo chown -R "$SVC_USER:$SVC_USER" "$APP_DIR/apps/web/.next"
for p in "$APP_DIR/apps/api/dist" "$APP_DIR/packages/shared/dist" \
         "$APP_DIR/node_modules" "$APP_DIR/apps/api/node_modules" \
         "$APP_DIR/apps/web/node_modules" "$APP_DIR/packages/shared/node_modules" \
         "$APP_DIR/apps/api/prisma"; do
  [[ -e "$p" ]] && sudo chmod -R a+rX "$p"
done
# Traversal only on the parents, so hms can reach the paths above.
sudo chmod a+x "$APP_DIR" "$APP_DIR/apps" "$APP_DIR/apps/api" \
               "$APP_DIR/apps/web" "$APP_DIR/packages" "$APP_DIR/packages/shared"
sudo chmod 600 "$APP_DIR/.env"
ok "hms can read the build; .env stays 0600"

# ── restart ─────────────────────────────────────────────────────────────────
log "Restart"
sudo systemctl enable smart-hospital-api smart-hospital-web >/dev/null 2>&1
sudo systemctl restart smart-hospital-api
sleep 4
sudo systemctl restart smart-hospital-web
sleep 6
ok "units restarted"

# ── verify ──────────────────────────────────────────────────────────────────
log "Verify"
FAIL=0

for unit in smart-hospital-api smart-hospital-web nginx postgresql; do
  if systemctl is-active --quiet "$unit"; then
    ok "$unit active"
  else
    printf '  \033[31m✗\033[0m %s NOT active\n' "$unit"; FAIL=1
  fi
done

# No dedicated /health route exists yet (see docs/DEPLOYMENT.md §8.3);
# /api/v1/meta is the cheapest thing that proves the API is really serving.
for i in $(seq 1 10); do
  API_CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 http://127.0.0.1:4000/api/v1/meta || echo 000)
  [[ "$API_CODE" =~ ^(200|401|404)$ ]] && break
  sleep 3
done
[[ "$API_CODE" =~ ^(200|401|404)$ ]] \
  && ok "API responding on :4000 (HTTP $API_CODE)" \
  || { printf '  \033[31m✗\033[0m API not responding (HTTP %s)\n' "$API_CODE"; FAIL=1; }

for i in $(seq 1 10); do
  WEB_CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 http://127.0.0.1:3001/login || echo 000)
  [[ "$WEB_CODE" == "200" ]] && break
  sleep 3
done
[[ "$WEB_CODE" == "200" ]] \
  && ok "web responding on :3001 (HTTP $WEB_CODE)" \
  || { printf '  \033[31m✗\033[0m web not responding (HTTP %s)\n' "$WEB_CODE"; FAIL=1; }

PROXY_CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 http://127.0.0.1/login || echo 000)
[[ "$PROXY_CODE" == "200" ]] \
  && ok "nginx proxying (HTTP $PROXY_CODE)" \
  || { printf '  \033[31m✗\033[0m nginx not proxying (HTTP %s)\n' "$PROXY_CODE"; FAIL=1; }

log "Memory"
free -h | head -2

if [[ "$FAIL" != "0" ]]; then
  printf '\n\033[1;31mDeploy finished with failures.\033[0m\n'
  echo "  sudo journalctl -u smart-hospital-api -n 60 --no-pager"
  echo "  sudo journalctl -u smart-hospital-web -n 60 --no-pager"
  exit 1
fi

log "Release complete"
