'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Plus, LogOut, Printer, Receipt } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import type { IpdAdmissionDetailDto, IpdAdmissionDto, IpdTab } from '@smart-hospital/shared';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { useToast } from '@/components/ui/toast';
import { ExportMenu } from '@/components/ui/export-menu';
import type { ExportTable } from '@/lib/export';
import { AdmissionForm } from './admission-form';
import { DischargeModalById } from '@/components/emr/discharge-modal';
import { printDischargeCard } from '@/lib/print';
import { api } from '@/lib/api';
import { useIpdAdmissions } from '@/lib/hooks/use-ipd';
import { useAbility } from '@/lib/auth-store';

const TABS: { value: IpdTab; label: string }[] = [
  { value: 'admitted', label: 'Admitted' },
  { value: 'discharged', label: 'Discharged Patient' },
];

export default function IpdPage() {
  const ability = useAbility();
  const canAdd = ability.can('ipd', 'add');
  const canEdit = ability.can('ipd', 'edit');

  const params = useSearchParams();
  const [tab, setTab] = useState<IpdTab>('admitted');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(25);
  const [open, setOpen] = useState(false);
  const [dischargingId, setDischargingId] = useState<string | null>(null);

  // Quick-create from the patient list: ?new=1&patientId=…&patientName=…
  const presetPatientId = params.get('patientId') ?? '';
  const presetPatientName = params.get('patientName') ?? '';
  useEffect(() => {
    if (params.get('new') === '1' && canAdd) setOpen(true);
  }, [params, canAdd]);

  const { data, isLoading, error } = useIpdAdmissions(tab, { search, page, size });
  const qc = useQueryClient();
  const toast = useToast();

  function exportTable(): ExportTable {
    const rows = data?.data ?? [];
    if (tab === 'discharged') {
      return {
        title: 'IPD Discharged Patients',
        filename: 'ipd-discharged',
        headers: ['Name', 'Patient ID', 'Case ID', 'Gender', 'Phone', 'Generated By', 'Consultant', 'Admission Date', 'Discharged Date', 'Tax', 'Net Amount', 'Total'],
        rows: rows.map((a) => [
          a.patientName, a.patientId, a.caseNo ?? '', a.patientGender ?? '', a.patientPhone ?? '', a.createdByName ?? '',
          a.consultantName, new Date(a.admissionDate).toLocaleDateString(),
          a.dischargeDate ? new Date(a.dischargeDate).toLocaleDateString() : '',
          a.taxAmount.toFixed(2), a.billedAmount.toFixed(2), a.billedAmount.toFixed(2),
        ]),
      };
    }
    return {
      title: 'IPD Admissions',
      filename: 'ipd-admissions',
      headers: ['IPD No', 'Case ID', 'Patient', 'Gender', 'Phone', 'Generated By', 'Consultant', 'Bed', 'Is Antenatal', 'Previous Medical Issue', 'Credit'],
      rows: rows.map((a) => [
        a.ipdNo, a.caseNo ?? '', a.patientName, a.patientGender ?? '', a.patientPhone ?? '', a.createdByName ?? '',
        a.consultantName, a.bedLabel, a.isAntenatal ? 'Yes' : 'No', a.previousMedicalIssue ?? '', a.creditLimit.toFixed(0),
      ]),
    };
  }

  /** The card is printed from the captured discharge fields, which only the detail carries. */
  async function onPrintCard(a: IpdAdmissionDto) {
    try {
      const detail = await qc.fetchQuery({
        queryKey: ['ipd-detail', a.id],
        queryFn: () => api.get<IpdAdmissionDetailDto>(`/ipd/${a.id}`),
      });
      printDischargeCard(detail);
    } catch (e) {
      toast.error('Could not load the discharge card', { description: (e as Error).message });
    }
  }

  const admittedColumns: Column<IpdAdmissionDto>[] = [
    { key: 'ipdNo', header: 'IPD No', className: 'font-medium' },
    { key: 'caseNo', header: 'Case ID', render: (a) => a.caseNo ?? '—' },
    { key: 'patientName', header: 'Name' },
    { key: 'patientGender', header: 'Gender', render: (a) => a.patientGender ?? '—' },
    { key: 'patientPhone', header: 'Phone', render: (a) => a.patientPhone ?? '—' },
    { key: 'createdByName', header: 'Generated By', render: (a) => a.createdByName ?? '—' },
    { key: 'consultantName', header: 'Consultant Doctor' },
    { key: 'bedLabel', header: 'Bed' },
    { key: 'isAntenatal', header: 'Is Antenatal', render: (a) => (a.isAntenatal ? 'Yes' : 'No') },
    { key: 'previousMedicalIssue', header: 'Previous Medical Issue', className: 'text-fg-muted', render: (a) => a.previousMedicalIssue ?? '—' },
    { key: 'creditLimit', header: 'Credit Limit ($)', className: 'tabular', render: (a) => a.creditLimit.toFixed(2) },
  ];

  const dischargedColumns: Column<IpdAdmissionDto>[] = [
    { key: 'patientName', header: 'Name', className: 'font-medium' },
    { key: 'patientId', header: 'Patient Id', render: (a) => a.patientId.slice(0, 8) },
    { key: 'caseNo', header: 'Case ID', render: (a) => a.caseNo ?? '—' },
    { key: 'patientGender', header: 'Gender', render: (a) => a.patientGender ?? '—' },
    { key: 'patientPhone', header: 'Phone', render: (a) => a.patientPhone ?? '—' },
    { key: 'createdByName', header: 'Generated By', render: (a) => a.createdByName ?? '—' },
    { key: 'consultantName', header: 'Consultant Doctor' },
    { key: 'admissionDate', header: 'Admission Date', render: (a) => new Date(a.admissionDate).toLocaleString() },
    { key: 'dischargeDate', header: 'Discharged Date', render: (a) => (a.dischargeDate ? new Date(a.dischargeDate).toLocaleString() : '—') },
    { key: 'taxAmount', header: 'Tax ($)', className: 'tabular', render: (a) => a.taxAmount.toFixed(2) },
    { key: 'billedAmount', header: 'Net Amount ($)', className: 'tabular', render: (a) => a.billedAmount.toFixed(2) },
    { key: 'total', header: 'Total ($)', className: 'tabular', render: (a) => a.billedAmount.toFixed(2) },
  ];

  return (
    <div className="space-y-4">
      <PageHeader
        title="IPD – In Patient"
        description="Admit inpatients to beds with credit limit and discharge"
        actions={canAdd && (
          <Button onClick={() => setOpen(true)}>
            <Plus className="h-4 w-4" /> Add Patient
          </Button>
        )}
      >
        <Tabs tabs={TABS} value={tab} onChange={(t) => { setTab(t); setPage(1); }} />
      </PageHeader>

      <DataTable
        columns={tab === 'discharged' ? dischargedColumns : admittedColumns}
        rows={data?.data ?? []}
        meta={data?.meta}
        loading={isLoading}
        error={error ? 'Failed to load admissions' : undefined}
        search={search}
        onSearch={(v) => { setSearch(v); setPage(1); }}
        onPage={setPage}
        onSize={(s) => { setSize(s); setPage(1); }}
        toolbar={<ExportMenu table={exportTable} />}
        rowActions={(a) => (
          <>
            <Link
              href={`/ipd/${a.id}`}
              aria-label="View admission"
              title="View admission"
              className="flex h-7 items-center gap-1 rounded-sm px-2 text-xs text-fg-muted hover:bg-primary/10 hover:text-primary"
            >
              <Receipt className="h-4 w-4" /> Details
            </Link>
            {tab === 'admitted' && canEdit && (
              <button
                onClick={() => setDischargingId(a.id)}
                aria-label="Discharge"
                className="flex items-center gap-1 rounded-sm px-2 py-1 text-xs text-danger hover:bg-danger/10"
              >
                <LogOut className="h-3.5 w-3.5" /> Discharge
              </button>
            )}
            <button
              onClick={() => onPrintCard(a)}
              aria-label="Print card"
              className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-border/50"
            >
              <Printer className="h-4 w-4" />
            </button>
          </>
        )}
      />

      {dischargingId && (
        <DischargeModalById
          admissionId={dischargingId}
          onClose={() => setDischargingId(null)}
          onDone={() => toast.success('Patient discharged · bed freed')}
        />
      )}

      <AdmissionForm
        open={open}
        onClose={() => setOpen(false)}
        initialPatientId={presetPatientId}
        initialPatientLabel={presetPatientName}
      />
    </div>
  );
}
