'use client';

import { Pencil, Printer, Trash2 } from 'lucide-react';
import { IconButton } from '@/components/ui/button';
import { Modal } from '@/components/ui/modal';
import { SkeletonText } from '@/components/ui/skeleton';
import type { BloodIssueDto } from '@smart-hospital/shared';
import { useBloodIssue } from '@/lib/hooks/use-departments';
import { printBloodIssueBill } from '@/lib/print';

/** "Bill Details" for a Blood/Component Issue — full field grid matching the demo. */
export function BloodIssueDetailsModal({
  id, title, open, onClose, onEdit, onDelete, canEdit, canDelete,
}: {
  id: string | null;
  title: string;
  open: boolean;
  onClose: () => void;
  onEdit?: (issue: BloodIssueDto) => void;
  onDelete?: (issue: BloodIssueDto) => void;
  canEdit?: boolean;
  canDelete?: boolean;
}) {
  const { data, isLoading } = useBloodIssue(open ? id : null);

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Bill Details"
      size="xl"
      headerActions={
        data ? (
          <>
            <IconButton label="Print bill" tone="primary" onClick={() => printBloodIssueBill(title, data)}>
              <Printer className="h-4 w-4" />
            </IconButton>
            {canEdit && onEdit && (
              <IconButton label="Edit issue" tone="primary" onClick={() => onEdit(data)}>
                <Pencil className="h-4 w-4" />
              </IconButton>
            )}
            {canDelete && onDelete && (
              <IconButton label="Delete issue" tone="danger" onClick={() => onDelete(data)}>
                <Trash2 className="h-4 w-4" />
              </IconButton>
            )}
          </>
        ) : null
      }
    >
      <div className="space-y-5">
          {isLoading || !data ? (
            <SkeletonText lines={6} />
          ) : (
            <div className="grid grid-cols-1 gap-x-8 gap-y-1 text-sm sm:grid-cols-4">
              <Row label="Bill No" value={data.billNo} />
              <Row label="Case ID" value={data.caseNo ?? '—'} />
              <Row label="Received To" value={data.patientName} />
              <Row label="Total" value={`#${data.subtotal.toFixed(2)}`} />

              <Row label="Issue Date" value={new Date(data.issueDate).toLocaleString()} />
              <Row label="Blood Group" value={data.bloodGroup ?? '—'} />
              <Row label="Bags" value={data.bagNo ?? '—'} />
              <Row label="Total Discount" value={`#${data.discount.toFixed(2)}`} />

              <Row label="Reference" value={data.referenceDoctor ?? '—'} />
              <Row label="Donor Name" value={data.donorName ?? '—'} />
              <Row label="Technician" value={data.technician ?? '—'} />
              <Row label="Total Tax" value={`#${data.tax.toFixed(2)}`} />

              <Row label="Hospital Doctor" value={data.consultantName ?? '—'} />
              <Row label="Component" value={data.component ?? '—'} />
              <Row label="Blood Qty" value={data.bloodQty ?? '—'} />
              <Row label="Net Amount" value={`#${data.netAmount.toFixed(2)}`} />

              <Row label="Note" value={data.note ?? '—'} />
              <Row label="Generated By" value={data.createdByName ?? '—'} />
              <Row label="Total Deposit" value={`#${data.paid.toFixed(2)}`} />
              <Row label="Balance Amount" value={`#${data.balance.toFixed(2)}`} />
            </div>
          )}
      </div>
    </Modal>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4 border-b border-line/50 py-1.5">
      <span className="text-fg-muted">{label}</span>
      <span className="text-right font-medium">{value}</span>
    </div>
  );
}
