'use client';

import { useState } from 'react';
import { Plus, Eye, CreditCard, Printer, UploadCloud, ShoppingCart, Pill, Trash2 } from 'lucide-react';
import type { InvoiceDto, MedicineDto } from '@smart-hospital/shared';
import { DataTable, type Column, type SortState } from '@/components/ui/data-table';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { useToast } from '@/components/ui/toast';
import { useConfirm } from '@/components/ui/confirm-dialog';
import { ExportMenu } from '@/components/ui/export-menu';
import type { ExportTable } from '@/lib/export';
import { DeptBillForm } from '@/components/dept-bill-form';
import { useInvoices } from '@/lib/hooks/use-clinical';
import { useMedicines, useDeleteMedicines, useGeneratePharmacyBill, useDeletePharmacyBill } from '@/lib/hooks/use-departments';
import { useAbility } from '@/lib/auth-store';
import { MedicineForm } from '@/components/emr/medicine-form';
import { MedicineDetailsModal } from '@/components/emr/medicine-details-modal';
import { MedicineImportModal } from '@/components/emr/medicine-import-modal';
import { MedicinePurchasePanel } from '@/components/emr/medicine-purchase-panel';
import { PharmacyBillDetailsModal } from '@/components/emr/pharmacy-bill-details-modal';
import { PharmacyBillEditModal } from '@/components/emr/pharmacy-bill-edit-modal';
import { PharmacyPaymentsModal } from '@/components/emr/pharmacy-payments-modal';
import { printPharmacyBill } from '@/lib/print';

type Tab = 'bills' | 'medicines' | 'purchase';

/** "12.50%" — the rate a money column represents, as the reference prints it. */
function pct(part: number, whole: number): string {
  return `${whole > 0 ? ((part / whole) * 100).toFixed(2) : '0.00'}%`;
}

export default function PharmacyPage() {
  const ability = useAbility();
  const canAdd = ability.can('pharmacy', 'add');
  const canEdit = ability.can('pharmacy', 'edit');
  const canDelete = ability.can('pharmacy', 'delete');

  const [tab, setTab] = useState<Tab>('bills');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  // Both lists passed `onSize={() => {}}`: the rows-per-page control rendered
  // and reacted to clicks, but the query never changed, so picking 100 did
  // nothing. Real state, and a sort the API now honours.
  const [size, setSize] = useState(25);
  const [sort, setSort] = useState<SortState | undefined>();

  // Pharmacy Bill state
  const [billOpen, setBillOpen] = useState(false);
  const [billDetailId, setBillDetailId] = useState<string | null>(null);
  const [paymentsId, setPaymentsId] = useState<string | null>(null);
  const [editingBill, setEditingBill] = useState<InvoiceDto | null>(null);

  // Medicines Stock state
  const [medOpen, setMedOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [medDetailId, setMedDetailId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const sortParam = sort ? `${sort.key}:${sort.dir}` : undefined;
  const invoices = useInvoices('pharmacy', { search, page, size, sort: sortParam });
  const medicines = useMedicines({ search, page, size, sort: sortParam });
  const genBill = useGeneratePharmacyBill();
  const deleteBill = useDeletePharmacyBill();
  const deleteMeds = useDeleteMedicines();
  const toast = useToast();
  const confirm = useConfirm();

  function toggleSort(key: string) {
    setSort((cur) =>
      cur?.key !== key ? { key, dir: 'asc' } : cur.dir === 'asc' ? { key, dir: 'desc' } : undefined,
    );
    setPage(1);
  }

  function switchTab(t: Tab) {
    setTab(t);
    setPage(1);
    setSearch('');
    // The tabs sort on different columns; a carried-over sort would be dropped
    // by the API's whitelist and look like the control had failed.
    setSort(undefined);
    setSelected(new Set());
  }

  function billExportTable(): ExportTable {
    const rows = invoices.data?.data ?? [];
    return {
      title: 'Pharmacy Bill',
      filename: 'pharmacy-bills',
      headers: ['Bill No', 'Case ID', 'Date', 'Patient Name', 'Generated By', 'Doctor Name', 'Amount', 'Discount', 'Tax', 'Net Amount', 'Paid Amount', 'Refund Amount', 'Balance Amount'],
      rows: rows.map((i) => [
        i.billNo, i.caseNo ?? '', new Date(i.billDate).toLocaleString(), i.patientName, i.createdByName ?? '', i.consultantName ?? '',
        i.subtotal.toFixed(2), `${i.discount.toFixed(2)} (${pct(i.discount, i.subtotal)})`, `${i.tax.toFixed(2)} (${pct(i.tax, i.subtotal)})`,
        i.netAmount.toFixed(2), i.paid.toFixed(2), i.refund.toFixed(2), i.balance.toFixed(2),
      ]),
    };
  }

  const billCols: Column<InvoiceDto>[] = [
    { key: 'billNo', sortable: true, header: 'Bill No', className: 'font-medium' },
    { key: 'caseNo', header: 'Case ID', render: (i) => i.caseNo ?? '—' },
    { key: 'billDate', sortable: true, header: 'Date', render: (i) => new Date(i.billDate).toLocaleString() },
    { key: 'patientName', header: 'Patient Name' },
    { key: 'createdByName', header: 'Generated By', render: (i) => i.createdByName ?? '—' },
    { key: 'consultantName', header: 'Doctor Name', render: (i) => i.consultantName ?? '—' },
    { key: 'subtotal', sortable: true, header: 'Amount (#)', className: 'tabular', render: (i) => i.subtotal.toFixed(2) },
    // The reference prints both of these as "amount (pct%)" — the rate matters
    // as much as the money when scanning a list of bills.
    { key: 'discount', sortable: true, header: 'Discount (#)', className: 'tabular', render: (i) => `${i.discount.toFixed(2)} (${pct(i.discount, i.subtotal)})` },
    { key: 'tax', sortable: true, header: 'Tax (#)', className: 'tabular', render: (i) => `${i.tax.toFixed(2)} (${pct(i.tax, i.subtotal)})` },
    { key: 'netAmount', sortable: true, header: 'Net Amount (#)', className: 'tabular', render: (i) => i.netAmount.toFixed(2) },
    { key: 'paid', sortable: true, header: 'Paid Amount (#)', className: 'tabular', render: (i) => i.paid.toFixed(2) },
    { key: 'refund', sortable: true, header: 'Refund Amount (#)', className: 'tabular', render: (i) => i.refund.toFixed(2) },
    {
      key: 'balance', header: 'Balance Amount (#)', className: 'tabular',
      render: (i) => <span className={i.balance > 0 ? 'text-warning' : 'text-success'}>{i.balance.toFixed(2)}</span>,
    },
  ];

  function medExportTable(): ExportTable {
    const rows = medicines.data?.data ?? [];
    return {
      title: 'Medicines Stock',
      filename: 'medicines-stock',
      headers: ['Medicine Name', 'Medicine Company', 'Medicine Composition', 'Medicine Category', 'Medicine Group', 'Unit', 'Available Qty'],
      rows: rows.map((m) => [m.name, m.companyName ?? '', m.composition ?? '', m.categoryName ?? '', m.groupName ?? '', m.unitName ?? '', String(m.stock)]),
    };
  }

  const medCols: Column<MedicineDto>[] = [
    { key: 'name', sortable: true, header: 'Medicine Name', className: 'font-medium' },
    { key: 'companyName', header: 'Medicine Company', render: (m) => m.companyName ?? '—' },
    { key: 'composition', sortable: true, header: 'Medicine Composition', render: (m) => m.composition ?? '—' },
    { key: 'categoryName', header: 'Medicine Category', render: (m) => m.categoryName ?? '—' },
    { key: 'groupName', header: 'Medicine Group', render: (m) => m.groupName ?? '—' },
    { key: 'unitName', header: 'Unit', render: (m) => m.unitName ?? '—' },
    {
      key: 'stock',
      header: 'Available Qty',
      className: 'tabular',
      render: (m) => (
        <span>
          {m.stock}{' '}
          {m.isOutOfStock && <span className="text-danger">(Out of Stock)</span>}
          {!m.isOutOfStock && m.needsReorder && <span className="text-warning">(Reorder)</span>}
        </span>
      ),
    },
  ];

  return (
    <div className="space-y-4">
      <PageHeader
        title="Pharmacy"
        description="Sale bills, medicine catalog, and procurement"
        actions={
          <>
          {tab === 'bills' && (
            <>
              <Button variant="secondary" onClick={() => switchTab('medicines')}>
                <Pill className="h-4 w-4" /> Medicines
              </Button>
              {canAdd && <Button onClick={() => setBillOpen(true)}><Plus className="h-4 w-4" /> Generate Bill</Button>}
            </>
          )}
          {tab === 'medicines' && (
            <>
              {canAdd && (
                <Button variant="secondary" onClick={() => setImportOpen(true)}>
                  <UploadCloud className="h-4 w-4" /> Import Medicines
                </Button>
              )}
              {canAdd && <Button onClick={() => setMedOpen(true)}><Plus className="h-4 w-4" /> Add Medicine</Button>}
              <Button variant="secondary" onClick={() => switchTab('purchase')}>
                <ShoppingCart className="h-4 w-4" /> Purchase
              </Button>
            </>
          )}
          </>
        }
      >
        <Tabs
          tabs={[
            { value: 'bills', label: 'Pharmacy Bill' },
            { value: 'medicines', label: 'Medicines Stock' },
            { value: 'purchase', label: 'Purchase' },
          ]}
          value={tab}
          onChange={(t) => switchTab(t as Tab)}
        />
      </PageHeader>

      {tab === 'bills' && (
        <DataTable
          columns={billCols}
          rows={invoices.data?.data ?? []}
          meta={invoices.data?.meta}
          loading={invoices.isLoading}
          search={search}
          onSearch={(v) => { setSearch(v); setPage(1); }}
          onPage={setPage}
          onSize={(v) => { setSize(v); setPage(1); }}
          sort={sort}
          onSort={toggleSort}
          toolbar={<ExportMenu table={billExportTable} />}
          rowActions={(i) => (
            <>
              <button onClick={() => setBillDetailId(i.id)} aria-label="Details" title="Bill Details" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Eye className="h-4 w-4" />
              </button>
              <button onClick={() => setPaymentsId(i.id)} aria-label="Payments" title="Payments" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <CreditCard className="h-4 w-4" />
              </button>
              <button onClick={() => printPharmacyBill(i)} aria-label="Print" title="Print" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Printer className="h-4 w-4" />
              </button>
            </>
          )}
        />
      )}

      {tab === 'medicines' && (
        <DataTable
          columns={medCols}
          rows={medicines.data?.data ?? []}
          meta={medicines.data?.meta}
          loading={medicines.isLoading}
          search={search}
          onSearch={(v) => { setSearch(v); setPage(1); }}
          onPage={setPage}
          onSize={(v) => { setSize(v); setPage(1); }}
          sort={sort}
          onSort={toggleSort}
          selectable
          selected={selected}
          onToggle={(id) => setSelected((s) => { const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n; })}
          onToggleAll={(ids) => setSelected((s) => (s.size === ids.length ? new Set() : new Set(ids)))}
          toolbar={
            <>
              <ExportMenu table={medExportTable} />
              {canDelete && selected.size > 0 && (
                <Button
                  variant="danger"
                  size="sm"
                  onClick={async () => {
                    const count = selected.size;
                    const ok = await confirm({
                      title: `Delete ${count} medicine${count === 1 ? '' : 's'}?`,
                      description: 'The selected medicines and their stock records will be removed. This cannot be undone.',
                      confirmLabel: `Delete ${count}`,
                      tone: 'danger',
                    });
                    if (!ok) return;
                    try {
                      await deleteMeds.mutateAsync({ ids: [...selected] });
                      setSelected(new Set());
                      toast.success(`${count} medicine${count === 1 ? '' : 's'} deleted`);
                    } catch (e) {
                      toast.error('Could not delete medicines', { description: (e as Error).message });
                    }
                  }}
                >
                  <Trash2 className="h-4 w-4" /> Delete Selected
                </Button>
              )}
            </>
          }
          rowActions={(m) => (
            <button onClick={() => setMedDetailId(m.id)} aria-label="Details" title="Details" className="flex h-7 items-center gap-1 rounded-sm px-2 text-xs text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Eye className="h-4 w-4" /> Details
            </button>
          )}
        />
      )}

      {tab === 'purchase' && <MedicinePurchasePanel />}

      {/* Generate pharmacy bill */}
      <DeptBillForm
        open={billOpen}
        title="Generate Pharmacy Bill"
        catalog={(medicines.data?.data ?? []).map((m) => ({ id: m.id, name: m.name, price: m.salePrice }))}
        submitting={genBill.isPending}
        onClose={() => setBillOpen(false)}
        onSubmit={({ patientId, lines, payment }) =>
          genBill.mutateAsync({
            patientId,
            items: lines.map((l) => ({
              medicineId: l.chargeId!,
              name: l.name,
              qty: l.qty,
              appliedCharge: l.appliedCharge,
              discountPct: l.discountPct,
              taxPct: l.taxPct,
            })),
            payment,
          })
        }
      />

      <PharmacyBillDetailsModal
        id={billDetailId}
        open={!!billDetailId}
        onClose={() => setBillDetailId(null)}
        canEdit={canEdit}
        canDelete={canDelete}
        onEdit={(b) => { setBillDetailId(null); setEditingBill(b); }}
        onDelete={async (b) => {
          const ok = await confirm({
            title: `Delete bill ${b.billNo}?`,
            description: 'The bill is voided and the dispensed medicines are returned to stock. This cannot be undone.',
            confirmLabel: 'Delete bill',
            tone: 'danger',
          });
          if (!ok) return;
          try {
            await deleteBill.mutateAsync(b.id);
            toast.success(`${b.billNo} deleted — stock returned`);
            setBillDetailId(null);
          } catch (e) {
            toast.error('Could not delete bill', { description: (e as Error).message });
          }
        }}
      />
      <PharmacyBillEditModal bill={editingBill} open={!!editingBill} onClose={() => setEditingBill(null)} />
      <PharmacyPaymentsModal id={paymentsId} open={!!paymentsId} onClose={() => setPaymentsId(null)} />

      <MedicineForm open={medOpen} onClose={() => setMedOpen(false)} />
      <MedicineImportModal open={importOpen} onClose={() => setImportOpen(false)} />
      <MedicineDetailsModal id={medDetailId} open={!!medDetailId} onClose={() => setMedDetailId(null)} canEdit={canEdit} canDelete={canDelete} />
    </div>
  );
}
