'use client';

import { PageHeader } from '@/components/ui/page-header';
import { useToast } from '@/components/ui/toast';
import { useConfirm } from '@/components/ui/confirm-dialog';
import { useState } from 'react';
import { Eye, Pencil, Plus, Printer, Trash2 } from 'lucide-react';
import type { BirthRecordDto, DeathRecordDto } from '@smart-hospital/shared';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ExportMenu } from '@/components/ui/export-menu';
import type { ExportTable } from '@/lib/export';
import { useBirths, useDeaths, useDeleteBirth, useDeleteDeath } from '@/lib/hooks/use-office';
import { useAbility } from '@/lib/auth-store';
import { printBirthRecord, printDeathRecord } from '@/lib/print';
import { BirthRecordForm } from '@/components/emr/birth-record-form';
import { BirthRecordDetailsModal } from '@/components/emr/birth-record-details-modal';
import { DeathRecordForm } from '@/components/emr/death-record-form';
import { DeathRecordDetailsModal } from '@/components/emr/death-record-details-modal';

type Tab = 'birth' | 'death';

export default function BirthDeathPage() {
  const [tab, setTab] = useState<Tab>('birth');

  return (
    <div className="space-y-4">
      <PageHeader title="Birth &amp; Death Record" description="Register births and deaths with printable reports" />

      <Tabs tabs={[{ value: 'birth', label: 'Birth Record' }, { value: 'death', label: 'Death Record' }]} value={tab} onChange={(t) => setTab(t as Tab)} />

      {tab === 'birth' ? <BirthPanel /> : <DeathPanel />}
    </div>
  );
}

function BirthPanel() {
  const ability = useAbility();
  const canAdd = ability.can('birth_death', 'add');
  const canEdit = ability.can('birth_death', 'edit');
  const canDelete = ability.can('birth_death', 'delete');

  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<BirthRecordDto | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);

  const births = useBirths({ search, page, size: 100 });
  const deleteBirth = useDeleteBirth();
  const toast = useToast();
  const confirm = useConfirm();

  function exportTable(): ExportTable {
    const rows = births.data?.data ?? [];
    return {
      title: 'Birth Record',
      filename: 'birth-records',
      headers: ['Reference No', 'Case ID', 'Generated By', 'Child Name', 'Gender', 'Birth Date', 'Mother Name', 'Father Name', 'Blood Group', 'Report'],
      rows: rows.map((b) => [b.referenceNo, b.caseNo ?? '', b.createdByName ?? '', b.childName, b.gender ?? '', new Date(b.birthDate).toLocaleString(), b.motherName ?? '', b.fatherName ?? '', b.bloodGroup ?? '', b.report ?? '']),
    };
  }

  const cols: Column<BirthRecordDto>[] = [
    { key: 'referenceNo', header: 'Reference No', className: 'font-medium' },
    { key: 'caseNo', header: 'Case ID', render: (b) => b.caseNo ?? '—' },
    { key: 'createdByName', header: 'Generated By', render: (b) => b.createdByName ?? '—' },
    { key: 'childName', header: 'Child Name' },
    { key: 'gender', header: 'Gender', render: (b) => b.gender ?? '—' },
    { key: 'birthDate', header: 'Birth Date', render: (b) => new Date(b.birthDate).toLocaleString() },
    { key: 'motherName', header: 'Mother Name', render: (b) => `${b.motherName ?? '—'}${b.patientNo ? ` (${b.patientNo})` : ''}` },
    { key: 'fatherName', header: 'Father Name', render: (b) => b.fatherName ?? '—' },
    { key: 'bloodGroup', header: 'Blood Group', render: (b) => b.bloodGroup ?? '—' },
    { key: 'report', header: 'Report', render: (b) => b.report ?? '—' },
  ];

  return (
    <div className="space-y-4">
      <DataTable
        columns={cols}
        rows={births.data?.data ?? []}
        meta={births.data?.meta}
        loading={births.isLoading}
        search={search}
        onSearch={(v) => { setSearch(v); setPage(1); }}
        onPage={setPage}
        onSize={() => {}}
        toolbar={
          <>
            <ExportMenu table={exportTable} />
            {canAdd && (
              <Button size="sm" onClick={() => { setEditing(null); setFormOpen(true); }}>
                <Plus className="h-4 w-4" /> Add Birth Record
              </Button>
            )}
          </>
        }
        rowActions={(b) => (
          <>
            <button onClick={() => setDetailId(b.id)} aria-label="Details" title="Show" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Eye className="h-4 w-4" />
            </button>
            {canEdit && (
              <button onClick={() => { setEditing(b); setFormOpen(true); }} aria-label="Edit" title="Edit" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Pencil className="h-4 w-4" />
              </button>
            )}
            <button onClick={() => printBirthRecord(b)} aria-label="Print" title="Print" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Printer className="h-4 w-4" />
            </button>
            {canDelete && (
              <button
                onClick={async () => {
                  const ok = await confirm({
                    title: `Delete birth record ${b.referenceNo}?`,
                    description: 'The record and its attachments will be removed. This cannot be undone.',
                    confirmLabel: 'Delete record',
                    tone: 'danger',
                  });
                  if (!ok) return;
                  try {
                    await deleteBirth.mutateAsync(b.id);
                    toast.success(`Birth record ${b.referenceNo} deleted`);
                  } catch (e) {
                    toast.error('The record and its attachments will be removed', { description: (e as Error).message });
                  }
                }}
                aria-label="Delete" title="Delete" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-danger/10 hover:text-danger"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </>
        )}
      />

      <BirthRecordForm open={formOpen} record={editing} onClose={() => setFormOpen(false)} />
      <BirthRecordDetailsModal id={detailId} open={!!detailId} onClose={() => setDetailId(null)} onEdit={() => { const b = births.data?.data.find((x) => x.id === detailId); if (b) { setEditing(b); setDetailId(null); setFormOpen(true); } }} />
    </div>
  );
}

function DeathPanel() {
  const ability = useAbility();
  const canAdd = ability.can('birth_death', 'add');
  const canEdit = ability.can('birth_death', 'edit');
  const canDelete = ability.can('birth_death', 'delete');

  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<DeathRecordDto | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);

  const deaths = useDeaths({ search, page, size: 100 });
  const deleteDeath = useDeleteDeath();
  const toast = useToast();
  const confirm = useConfirm();

  function exportTable(): ExportTable {
    const rows = deaths.data?.data ?? [];
    return {
      title: 'Death Record',
      filename: 'death-records',
      headers: ['Reference No', 'Case ID', 'Generated By', 'Patient Name', 'Guardian Name', 'Gender', 'Death Date', 'Blood Group', 'Report'],
      rows: rows.map((d) => [d.referenceNo, d.caseNo ?? '', d.createdByName ?? '', d.patientName, d.guardianName ?? '', d.gender ?? '', new Date(d.deathDate).toLocaleString(), d.bloodGroup ?? '', d.cause ?? '']),
    };
  }

  const cols: Column<DeathRecordDto>[] = [
    { key: 'referenceNo', header: 'Reference No', className: 'font-medium' },
    { key: 'caseNo', header: 'Case ID', render: (d) => d.caseNo ?? '—' },
    { key: 'createdByName', header: 'Generated By', render: (d) => d.createdByName ?? '—' },
    { key: 'patientName', header: 'Patient Name', render: (d) => `${d.patientName}${d.patientNo ? ` (${d.patientNo})` : ''}` },
    { key: 'guardianName', header: 'Guardian Name', render: (d) => d.guardianName ?? '—' },
    { key: 'gender', header: 'Gender', render: (d) => d.gender ?? '—' },
    { key: 'deathDate', header: 'Death Date', render: (d) => new Date(d.deathDate).toLocaleString() },
    { key: 'bloodGroup', header: 'Blood Group', render: (d) => d.bloodGroup ?? '—' },
    { key: 'cause', header: 'Report', render: (d) => d.cause ?? '—' },
  ];

  return (
    <div className="space-y-4">
      <DataTable
        columns={cols}
        rows={deaths.data?.data ?? []}
        meta={deaths.data?.meta}
        loading={deaths.isLoading}
        search={search}
        onSearch={(v) => { setSearch(v); setPage(1); }}
        onPage={setPage}
        onSize={() => {}}
        toolbar={
          <>
            <ExportMenu table={exportTable} />
            {canAdd && (
              <Button size="sm" onClick={() => { setEditing(null); setFormOpen(true); }}>
                <Plus className="h-4 w-4" /> Add Death Record
              </Button>
            )}
          </>
        }
        rowActions={(d) => (
          <>
            <button onClick={() => setDetailId(d.id)} aria-label="Details" title="Show" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Eye className="h-4 w-4" />
            </button>
            {canEdit && (
              <button onClick={() => { setEditing(d); setFormOpen(true); }} aria-label="Edit" title="Edit" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
                <Pencil className="h-4 w-4" />
              </button>
            )}
            <button onClick={() => printDeathRecord(d)} aria-label="Print" title="Print" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary">
              <Printer className="h-4 w-4" />
            </button>
            {canDelete && (
              <button
                onClick={async () => {
                  const ok = await confirm({
                    title: `Delete death record ${d.referenceNo}?`,
                    description: 'The record and its attachments will be removed. This cannot be undone.',
                    confirmLabel: 'Delete record',
                    tone: 'danger',
                  });
                  if (!ok) return;
                  try {
                    await deleteDeath.mutateAsync(d.id);
                    toast.success(`Death record ${d.referenceNo} deleted`);
                  } catch (e) {
                    toast.error('The record and its attachments will be removed', { description: (e as Error).message });
                  }
                }}
                aria-label="Delete" title="Delete" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-danger/10 hover:text-danger"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </>
        )}
      />

      <DeathRecordForm open={formOpen} record={editing} onClose={() => setFormOpen(false)} />
      <DeathRecordDetailsModal id={detailId} open={!!detailId} onClose={() => setDetailId(null)} onEdit={() => { const d = deaths.data?.data.find((x) => x.id === detailId); if (d) { setEditing(d); setDetailId(null); setFormOpen(true); } }} />
    </div>
  );
}
