'use client';

import { useMemo, useState } from 'react';
import { Paperclip, Pencil, Plus, Trash2 } from 'lucide-react';
import type { LedgerEntryDto } from '@smart-hospital/shared';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Tabs } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { FormDrawer } from '@/components/ui/form-drawer';
import { Field, TextInput, TextArea, Select } from '@/components/ui/field';
import { ExportMenu } from '@/components/ui/export-menu';
import { useCatalog } from '@/lib/hooks/use-masters';
import { useLedger, useCreateLedger, useUpdateLedger, useDeleteLedger } from '@/lib/hooks/use-finance';
import { useAbility } from '@/lib/auth-store';

type Kind = 'income' | 'expense';
const EMPTY = { name: '', invoiceNo: '', amount: '', headId: '', date: new Date().toISOString().slice(0, 10), documentUrl: '', description: '' };

function fmtDate(iso: string) {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? '—' : d.toLocaleDateString('en-GB').replace(/\//g, '-');
}

export default function FinancePage() {
  const ability = useAbility();
  const canAdd = ability.can('finance', 'add');
  const canEdit = ability.can('finance', 'edit');
  const canDelete = ability.can('finance', 'delete');

  const [kind, setKind] = useState<Kind>('income');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);

  const ledger = useLedger(kind, { search, page, size: 100 });
  const heads = useCatalog(kind === 'income' ? 'income-head' : 'expense-head', { size: 100 });
  const create = useCreateLedger(kind);
  const update = useUpdateLedger(kind);
  const del = useDeleteLedger(kind);

  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<LedgerEntryDto | null>(null);
  const [form, setForm] = useState(EMPTY);
  const [error, setError] = useState('');
  const label = kind === 'income' ? 'Income' : 'Expense';

  const rows = ledger.data?.data ?? [];

  function openAdd() { setEditing(null); setForm(EMPTY); setError(''); setOpen(true); }
  function openEdit(r: LedgerEntryDto) {
    setEditing(r);
    setForm({ name: r.name, invoiceNo: r.invoiceNo ?? '', amount: String(r.amount), headId: r.headId ?? '', date: r.date.slice(0, 10), documentUrl: r.documentUrl ?? '', description: r.description ?? '' });
    setError('');
    setOpen(true);
  }
  async function onFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setForm((f) => ({ ...f, documentUrl: String(reader.result) }));
    reader.readAsDataURL(file);
  }
  async function save() {
    if (!form.name.trim() || !form.headId || !form.amount || !form.date) { setError(`${label} Head, Name, Date and Amount are required.`); return; }
    const input = { name: form.name, invoiceNo: form.invoiceNo, headId: form.headId || null, amount: Number(form.amount) || 0, date: new Date(form.date), documentUrl: form.documentUrl, description: form.description };
    if (editing) await update.mutateAsync({ id: editing.id, input });
    else await create.mutateAsync(input);
    setOpen(false);
  }
  async function remove(r: LedgerEntryDto) {
    if (confirm(`Delete "${r.name}"?`)) await del.mutateAsync(r.id);
  }

  const cols: Column<LedgerEntryDto>[] = [
    { key: 'name', header: 'Name', className: 'font-medium text-primary' },
    { key: 'invoiceNo', header: 'Invoice Number', render: (r) => r.invoiceNo || '—' },
    { key: 'date', header: 'Date', render: (r) => fmtDate(r.date) },
    { key: 'description', header: 'Description', render: (r) => <span className="line-clamp-3 text-fg-muted">{r.description || '—'}</span> },
    { key: 'headName', header: `${label} Head`, render: (r) => r.headName ?? '—' },
    { key: 'generatedByName', header: 'Generated By', render: (r) => (r.generatedByName ? `${r.generatedByName}${r.generatedByNo ? ` (${r.generatedByNo})` : ''}` : '—') },
    { key: 'amount', header: 'Amount ($)', className: 'tabular', render: (r) => r.amount.toFixed(2) },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold">{label} List</h1>
        {canAdd && <Button onClick={openAdd}><Plus className="h-4 w-4" /> Add {label}</Button>}
      </div>

      <Tabs tabs={[{ value: 'income', label: 'Income' }, { value: 'expense', label: 'Expenses' }]}
        value={kind} onChange={(k) => { setKind(k as Kind); setPage(1); setSearch(''); }} />

      <DataTable
        columns={cols}
        rows={rows}
        meta={ledger.data?.meta}
        loading={ledger.isLoading}
        search={search}
        onSearch={(v) => { setSearch(v); setPage(1); }}
        onPage={setPage}
        onSize={() => {}}
        toolbar={<ExportMenu table={() => ({ title: `${label} List`, filename: kind, headers: ['Name', 'Invoice Number', 'Date', 'Description', `${label} Head`, 'Generated By', 'Amount ($)'], rows: rows.map((r) => [r.name, r.invoiceNo ?? '', fmtDate(r.date), r.description ?? '', r.headName ?? '', r.generatedByName ?? '', r.amount.toFixed(2)]) })} />}
        rowActions={(canEdit || canDelete) ? (r) => (
          <div className="flex gap-1">
            {canEdit && <button onClick={() => openEdit(r)} aria-label="Edit" title="Edit" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-primary/10 hover:text-primary"><Pencil className="h-4 w-4" /></button>}
            {canDelete && <button onClick={() => remove(r)} aria-label="Delete" title="Delete" className="flex h-7 w-7 items-center justify-center rounded-sm text-fg-muted hover:bg-danger/10 hover:text-danger"><Trash2 className="h-4 w-4" /></button>}
          </div>
        ) : undefined}
      />

      <FormDrawer open={open} title={editing ? `Edit ${label}` : `Add ${label}`} onClose={() => setOpen(false)} onSubmit={save} submitting={create.isPending || update.isPending}>
        <div className="space-y-4">
          {error && <p role="alert" className="rounded-sm bg-danger/10 px-3 py-2 text-sm text-danger">{error}</p>}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Field label={`${label} Head`} required>
              <Select value={form.headId} onChange={(e) => setForm((f) => ({ ...f, headId: e.target.value }))} placeholder="Select"
                options={(heads.data?.data ?? []).map((h) => ({ value: h.id, label: h.name }))} />
            </Field>
            <Field label="Name" required><TextInput value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} /></Field>
            <Field label="Invoice Number"><TextInput value={form.invoiceNo} onChange={(e) => setForm((f) => ({ ...f, invoiceNo: e.target.value }))} /></Field>
            <Field label="Date" required><TextInput type="date" value={form.date} onChange={(e) => setForm((f) => ({ ...f, date: e.target.value }))} /></Field>
            <Field label="Amount ($)" required><TextInput type="number" step="0.01" value={form.amount} onChange={(e) => setForm((f) => ({ ...f, amount: e.target.value }))} /></Field>
            <Field label="Attach Document">
              <label className="flex cursor-pointer items-center gap-2 rounded-sm border border-dashed border-border px-3 py-2 text-sm text-fg-muted hover:border-primary hover:text-primary">
                <Paperclip className="h-4 w-4" /> {form.documentUrl ? 'Document attached — replace' : 'Drop a file here or click'}
                <input type="file" className="hidden" onChange={onFile} />
              </label>
            </Field>
          </div>
          <Field label="Description"><TextArea rows={3} value={form.description} onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))} /></Field>
        </div>
      </FormDrawer>
    </div>
  );
}
